#!/usr/bin/env bash
set -euo pipefail

REMOTE_HOST="${REMOTE_HOST:-hermes-dev}"
REMOTE_DIR="${REMOTE_DIR:-/srv/repos/projects/club-content-platform}"
RUN_APPROVAL_PUBLISH_SMOKE="${RUN_APPROVAL_PUBLISH_SMOKE:-0}"
SMOKE_TIMEOUT_SECONDS="${SMOKE_TIMEOUT_SECONDS:-300}"
HEALTH_TIMEOUT_SECONDS="${HEALTH_TIMEOUT_SECONDS:-60}"
HEALTH_POLL_SECONDS="${HEALTH_POLL_SECONDS:-2}"

ssh "${REMOTE_HOST}" \
  "REPO_DIR='${REMOTE_DIR}' RUN_APPROVAL_PUBLISH_SMOKE='${RUN_APPROVAL_PUBLISH_SMOKE}' SMOKE_TIMEOUT_SECONDS='${SMOKE_TIMEOUT_SECONDS}' HEALTH_TIMEOUT_SECONDS='${HEALTH_TIMEOUT_SECONDS}' HEALTH_POLL_SECONDS='${HEALTH_POLL_SECONDS}' bash '${REMOTE_DIR}/scripts/pull_and_restart_vps.sh'"
